[package]
name = "bytes"
version = "1.0.0"
edition = "2024"
description = "Types and Traits for working with bytes"
authors = [ "Harsh Kumar Moroliya <hkmoroliya@gmail.com>" ]
keywords = [ "zero-copy", "buffers", "bytes", "io" ]

[features]
default = ["std"]
std = []

[dependencies]
