[package]
name = "quickie"
version = "0.1.0"
edition = "2021"
rust-version = "1.84.0"

[features]
default = ["std"]
std = []
serde = ["dep:serde"]

[dependencies]
serde = { version = "1.0.217", default-features = false, features = ["alloc"], optional = true }

[dev-dependencies]
serde_test = "1.0"
