[workspace]
resolver = "2"
members = [ "bytes" , "date" , "net"]

[workspace.package]
rust-version = "1.84.0"
edition = "2021"
authors = [ "Harsh Kumar Moroliya <hkmoroliya@gmail.com>" ]
keywords = [ 
  "bytes",
  "date",
  "time",
  "datetime",
  "chiya",
  "non-blocking",
  "web",
  "http",
  "server",
  "async",
  "async_io",
  "threads",
  "runtime"
]

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
